SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1440
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.9  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 700
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOT_DMG = 40

ALIEN_HEALTH = 100
ALIEN_SPEED = 50  # Speed of the alien ship
ALIEN_AVOID_FORCE = 200  # Force to move away from asteroids
ALIEN_SHOT_SPEED = 300  # Speed of alien shots
ALIEN_SHOOT_COOLDOWN = 1.5  # Cooldown time between shots (in seconds)
ALIEN_RADIUS = 25  # Alien ship's radius
ALIEN_SPAWN_RATE = 3.0

GLOBAL_COLLISION_MODIFIER = 0.002

LOOT_DROP_CHANCE = 0.7