# Screen dimensions
SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1440

# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.9  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Shots
SHOT_RADIUS = 5
SHOT_LIFETIME = 2000  # milliseconds
PLAYER_SHOT_SPEED = 700
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds
PLAYER_SHOT_DMG = 40

# Alien settings
ALIEN_SPEED = 50
ALIEN_SHOT_SPEED = 300
ALIEN_SHOOT_COOLDOWN = 1.5  # seconds
ALIEN_RADIUS = 25
ALIEN_HEALTH = ALIEN_RADIUS * 3
ALIEN_SPAWN_RATE = 3.0
ALIEN_SHOOTING_RANGE = 600
ALIEN_TURN_SPEED = PLAYER_TURN_SPEED * 1.5
ALIEN_MOVE_SPEED = PLAYER_SPEED * 1.5
ALIEN_COLOR = (50, 190, 50)

# Global settings
GLOBAL_COLLISION_MODIFIER = 0.002
LOOT_DROP_CHANCE = 0.7

# Black Hole (BLK) settings
BLACK_HOLE_X = 100
BLACK_HOLE_Y = 100
BLACK_HOLE_RADIUS = 75
BLACK_HOLE_FRICTION = 1
BLACK_HOLE_ANGULAR_FRICTION = 1

BLACK_HOLE_FAR_RADIUS = BLACK_HOLE_RADIUS * 10
BLACK_HOLE_NEAR = BLACK_HOLE_FAR_RADIUS / 4
BLACK_HOLE_MID_RADIUS = BLACK_HOLE_FAR_RADIUS / 2

BLACK_HOLE_COLOR = (150, 120, 160)
BLACK_HOLE_HEALTH = 1_000_000

BLACK_HOLE_COLLI_BUFFER = 15

BLACK_HOLE_NEAR_PULL = -100
BLACK_HOLE_MID_PULL = -10
BLACK_HOLE_FAR_PULL = -3
