alien_screams = [
            "Well, this is going to hurt like a black hole!", 
            "Fantastic! Another f***ing asteroid!", 
            "Oh great, the hull's doing that explodey thing again!", 
            "Just what I needed... a giant space rock up my a**!",
            "We're screwed! But hey, at least it\’s quick!", 
            "Eject? Eject where?! Into more f***ing rocks?!",
            "Tell my ex I still hate her!", 
            "This is why I quit my last job...", 
            "F***ing typical! Can\’t catch a break in this galaxy!",
            "Yeah, let\’s fly into the asteroid field, they said. Brilliant idea!",
            "Oh sure, NOW the shields fail!", 
            "This is why I don\’t do space travel sober!", 
            "Well, I'm out of here... oh wait, no, I\’m not!",
            "I'd flip the bird to these asteroids if my hands weren\’t shaking!",
            "We're crashing? No sh**, Sherlock!", 
            "Well, this is going to look GREAT on my résumé!",
            "If I survive this, I'm gonna kill the navigator!", 
            "Why do I feel like I\’ve done this before… oh right, last time I died!",
            "F*** it, let\’s just hit the big one!", 
            "Tell the fleet... actually, nevermind. F*** the fleet!",
            "Oh look! More f***ing asteroids! That\’s just f***ing lovely!",
            "Great, a beautiful end to a sh***y day!", 
            "I bet the ship explodes before I can finish this sente—",
            "Perfect! My last thought is going to be how much this f***ing sucks!",
            "Collision imminent? No sh**!",
            "Tell the stars they can shove it!",
            "Well, this is what I get for skipping flight school!", 
            "Well, at least I won\’t have to pay my bar tab!",
            "F*** me sideways with a plasma cannon! It\’s all over!"
        ]

explosion_list = ["CRASH!", "BLAM!", "BANG!", "BOOMSHAK!", "THWACK!", "SMASH!", "THOOM!", "ZAP!", "BLAST!", "KA-BLAST!", "KABLAM!", "WHOOSH!", "CRACK!", "THUD!", "WHAM!"]